### ISSUE TITLE
[p]ffpicker help error

### ISSUE THREAD

**Issue by aikaterna** [adorabilis/Adora-Cogs#2]
Using [p]help FFPicker to display the help for the cog results in:
```
[2019-09-17 09:59:52] [ERROR] red: Exception in command 'help'
Traceback (most recent call last):
  File "c:\envs\margaret\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\envs\margaret\lib\site-packages\redbot\core\commands\help.py", line 585, in red_help
    await ctx.bot.send_help_for(ctx, thing_to_get_help_for)
  File "c:\envs\margaret\lib\site-packages\redbot\core\bot.py", line 176, in send_help_for
    return await self._help_formatter.send_help(ctx, help_for)
  File "c:\envs\margaret\lib\site-packages\redbot\core\commands\help.py", line 103, in send_help
    await self.format_cog_help(ctx, help_for)
  File "c:\envs\margaret\lib\site-packages\redbot\core\commands\help.py", line 299, in format_cog_help
    splitted = description.split("\n\n")
AttributeError: 'Command' object has no attribute 'split'
```

**Comment by adorabilis** [comment]
Closing this issue as it seems to be inconclusive following the discussion in #4.
